version: '3.8'
services:
  lint:
    image: golangci/golangci-lint:v2.7.1
    volumes:
      - ".:/app"

  dev:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - ENV_TYPE=dev
    volumes:
      - ".:/app"
    working_dir: /app
